# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    base_data.subject_csv: '%kernel.project_dir%/resources/data/subject.csv'
    base_data.qualifier_csv: '%kernel.project_dir%/resources/data/qualifier.csv'
    altcha.enabled: '%env(bool:ALTCHA_ENABLED)%'
    altcha.secret_key: '%env(ALTCHA_SECRET_KEY)%'
    altcha.header_payload_key: 'X-Altcha-Payload'
    altcha.token_expiry_seconds: '%env(ALTCHA_TOKEN_EXPIRY_SECONDS)%'
    recipient.admin: '%env(RECIPIENT_ADMIN)%'
    email.sender: '%env(EMAIL_SENDER)%'
    app.name: 'NickMe'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Dto\Request\CustomRequestQueryValueResolver:
        tags:
          - { name: 'controller.argument_value_resolver', priority: 150 }

    AltchaOrg\Altcha\Altcha:
        arguments:
            $hmacKey: '%env(ALTCHA_SECRET_KEY)%'

    App\Service\Notification\Sender\EmailSender:
        arguments:
            $renderer: '@App\Service\Notification\Renderer\HtmlNotificationRenderer'
            $textRenderer: '@App\Service\Notification\Renderer\TextNotificationRenderer'

    _instanceof:
        # commands should be handled through command bus only
        App\MessageHandler\CommandHandler:
            tags:
                - { name: messenger.message_handler, bus: command.bus }
        # events should be handled through event bus only
        App\MessageHandler\EventHandler:
            tags:
                - { name: messenger.message_handler, bus: event.bus }



when@test:
    parameters:
        base_data.subject_csv: '%kernel.project_dir%/resources/data/subject_test.csv'
        base_data.qualifier_csv: '%kernel.project_dir%/resources/data/qualifier_test.csv'
        recipient.admin: 'admin@example.com'
        email.sender: 'admin@nick.me'
