nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: [ ]
        allow_headers: [ ]
        allow_methods: [ ]
        allow_private_network: false
        expose_headers: [ ]
        max_age: 0
        hosts: [ ]
        origin_regex: false
        forced_allow_origin_value: ~
        skip_same_as_origin: true
    paths:
        '^/':
            origin_regex: true
            allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
            allow_methods: ['GET', 'OPTIONS', 'POST']
            allow_headers: ['Content-Type', 'Authorization', 'X-Altcha-Payload']
            expose_headers: ['Link']
            max_age: 3600
