name: Discord CI - Tests
concurrency:
  group: ${{ github.ref }}.ci-discord
  cancel-in-progress: true
on:
  # CI should be able to run manually
  # which will be interpreted as a push on main 
  workflow_dispatch:
  # CI should run on pull requests and push on main branch
  # some steps are executed only on pushes on main branch
  pull_request:
    branches: [ "main" ]
    types: [opened, synchronize, reopened]
  push:
    branches: [ "main" ]
jobs:

  discord-tests:
    name: Run discord tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./discord
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      # check discord bot is actually buildable
      - name: Test build
        run: npm run build

      # run discord tests
      - name: Run unit tests tests
        id: run-discord-tests
        run: npm run test