name: Deployment

concurrency:
  group: ${{ github.ref }}.deploy
  cancel-in-progress: true

on:
  # deploy should be able to run manually or when staging succeeds
  workflow_dispatch:
  workflow_run:
    workflows: ["Staging"]
    types:
      - completed

jobs:
  deploy-backend:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Login to registry
        run: |
          echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login ${{ secrets.REGISTRY_HOST }} \
            -u "${{ secrets.REGISTRY_USERNAME }}" \
            --password-stdin

      # Build + tag main Docker image
      - name: Build main backend Docker image
        run: |
          docker build \
            -f docker/prod/frankenphp/Dockerfile \
            --progress=plain \
            --build-arg UID=${{ secrets.DOCKER_BUILD_UID }} --build-arg GID=${{ secrets.DOCKER_BUILD_GID }} --build-arg APP_USER=${{ secrets.DOCKER_BUILD_USER }} \
            -t ${{ secrets.REGISTRY_HOST }}/${{ secrets.BACKEND_IMAGE_NAME }}:sha-${{ github.sha }} \
            .

      - name: Push main backend Docker image
        run: |
          docker push ${{ secrets.REGISTRY_HOST }}/${{ secrets.BACKEND_IMAGE_NAME }}:sha-${{ github.sha }}
          docker tag ${{ secrets.REGISTRY_HOST }}/${{ secrets.BACKEND_IMAGE_NAME }}:sha-${{ github.sha }} ${{ secrets.REGISTRY_HOST }}/${{ secrets.BACKEND_IMAGE_NAME }}:latest
          docker push ${{ secrets.REGISTRY_HOST }}/${{ secrets.BACKEND_IMAGE_NAME }}:latest

      # Build + tag consumer Docker image
      - name: Build consumer Docker image
        run: |
          docker build \
            -f docker/prod/worker/Dockerfile \
            --progress=plain \
            --build-arg UID=${{ secrets.DOCKER_BUILD_UID }} --build-arg GID=${{ secrets.DOCKER_BUILD_GID }} --build-arg APP_USER=${{ secrets.DOCKER_BUILD_USER }} \
            -t ${{ secrets.REGISTRY_HOST }}/${{ secrets.BACKEND_CONSUMER_IMAGE_NAME }}:sha-${{ github.sha }} \
            .

      - name: Push consumer Docker image
        run: |
          docker push ${{ secrets.REGISTRY_HOST }}/${{ secrets.BACKEND_CONSUMER_IMAGE_NAME }}:sha-${{ github.sha }}
          docker tag ${{ secrets.REGISTRY_HOST }}/${{ secrets.BACKEND_CONSUMER_IMAGE_NAME }}:sha-${{ github.sha }} ${{ secrets.REGISTRY_HOST }}/${{ secrets.BACKEND_CONSUMER_IMAGE_NAME }}:latest
          docker push ${{ secrets.REGISTRY_HOST }}/${{ secrets.BACKEND_CONSUMER_IMAGE_NAME }}:latest

      - name: Deploy backend
        uses: appleboy/ssh-action@v1.2.4
        with:
            host: ${{ secrets.HOST }}
            port: ${{ secrets.HOST_SSH_PORT }}
            username: ${{ secrets.HOST_SSH_USERNAME }}
            key: ${{ secrets.HOST_SSH_KEY }}
            script: |
              cd /opt/deploy-tools
              ./deploy.sh ${{ secrets.HOST_BACKEND_APP_NAME }} sha-${{ github.sha }}

  deploy-frontend:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Login to registry
        run: |
          echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login ${{ secrets.REGISTRY_HOST }} \
            -u "${{ secrets.REGISTRY_USERNAME }}" \
            --password-stdin

      # Build + tag frontend Docker image
      - name: Build frontend Docker image
        run: |
          docker build \
            -f docker/prod/frontend/Dockerfile \
            --progress=plain \
            --build-arg UID=${{ secrets.DOCKER_BUILD_UID }} --build-arg GID=${{ secrets.DOCKER_BUILD_GID }} --build-arg APP_USER=${{ secrets.DOCKER_BUILD_USER }} \
            --build-arg VITE_API_BASE_URL=${{ secrets.API_BASE_URL }} --build-arg VITE_ALTCHA_CHALLENGE_URL=${{ secrets.ALTCHA_CHALLENGE_URL }} \
            --build-arg ALTCHA_ENABLED=true \
            -t ${{ secrets.REGISTRY_HOST }}/${{ secrets.FRONTEND_IMAGE_NAME }}:sha-${{ github.sha }} \
            .

      - name: Push frontend Docker image
        run: |
          docker push ${{ secrets.REGISTRY_HOST }}/${{ secrets.FRONTEND_IMAGE_NAME }}:sha-${{ github.sha }}
          docker tag ${{ secrets.REGISTRY_HOST }}/${{ secrets.FRONTEND_IMAGE_NAME }}:sha-${{ github.sha }} ${{ secrets.REGISTRY_HOST }}/${{ secrets.FRONTEND_IMAGE_NAME }}:latest
          docker push ${{ secrets.REGISTRY_HOST }}/${{ secrets.FRONTEND_IMAGE_NAME }}:latest

      - name: Deploy frontend
        uses: appleboy/ssh-action@v1.2.4
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.HOST_SSH_PORT }}
          username: ${{ secrets.HOST_SSH_USERNAME }}
          key: ${{ secrets.HOST_SSH_KEY }}
          script: |
            cd /opt/deploy-tools
            ./deploy.sh ${{ secrets.HOST_FRONTEND_APP_NAME }} sha-${{ github.sha }}